spring.application.name=fdlj-backend

# JWT
app.jwt.secret=0KWsNuN8Yqcro2/fk2TXqEzyIX/uFDvml7LjMrPV73B0t1XMByoKj5e/lLOMcVp2kPA2boz9E2nbSOKGkYvWsA==
app.jwt.expiration-ms=86400000

spring.datasource.url=jdbc:postgresql://localhost:5432/fdlj
spring.datasource.username=fdlj
spring.datasource.password=fdlj

spring.jpa.hibernate.ddl-auto=update