-- V1: Schema inicial de FDLJ.
-- Fiel al schema generado por Hibernate (fase 7-8, migración de ddl-auto a Flyway).
-- En bases existentes se hace baseline en esta versión; en bases nuevas se aplica completa.
-- Constraints con nombres reales generados por Hibernate para permitir ddl-auto=validate.

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username varchar(50) NOT NULL,
    email varchar(100) NOT NULL,
    password varchar(100) NOT NULL,
    role varchar(20) NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
    CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username),
    CONSTRAINT users_role_check CHECK (role IN ('ADMIN', 'PLAYER', 'HINCHADA'))
);

CREATE TABLE players (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar(100) NOT NULL,
    apellido varchar(100) NOT NULL,
    email varchar(100) NOT NULL,
    posicion varchar(20),
    activo boolean NOT NULL,
    user_id bigint,
    CONSTRAINT players_pkey PRIMARY KEY (id),
    CONSTRAINT ukpnrwm9bkjel7qss1ekm05j953 UNIQUE (email),
    CONSTRAINT ukr2bdiqerficgwok3omt8rwlxb UNIQUE (user_id),
    CONSTRAINT players_posicion_check CHECK (posicion IN ('ARQUERO', 'DEFENSOR', 'MEDIOCAMPISTA', 'DELANTERO')),
    CONSTRAINT fk3rfv9832bif6rea5edetib8it FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE hinchas (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar(100) NOT NULL,
    apellido varchar(100) NOT NULL,
    activo boolean NOT NULL,
    user_id bigint,
    CONSTRAINT hinchas_pkey PRIMARY KEY (id),
    CONSTRAINT ukfsas7m2of125jkx36r1ys3hy2 UNIQUE (user_id),
    CONSTRAINT fkdgm9614s4yvf7dccauvm4w9ui FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE matches (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    fecha_hora timestamp with time zone NOT NULL,
    lugar varchar(150),
    estado varchar(30) NOT NULL,
    goles_equipo_a integer,
    goles_equipo_b integer,
    CONSTRAINT matches_pkey PRIMARY KEY (id),
    CONSTRAINT matches_estado_check CHECK (estado IN ('PROGRAMADO', 'CONVOCATORIA_ABIERTA', 'CONVOCATORIA_CERRADA', 'EN_CURSO', 'FINALIZADO', 'CANCELADO'))
);

CREATE TABLE teams (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    match_id bigint NOT NULL,
    side varchar(10) NOT NULL,
    CONSTRAINT teams_pkey PRIMARY KEY (id),
    CONSTRAINT teams_side_check CHECK (side IN ('EQUIPO_A', 'EQUIPO_B')),
    CONSTRAINT uk_team_match_side UNIQUE (match_id, side),
    CONSTRAINT fkt57boyfe3de2gay7ltdpcxthl FOREIGN KEY (match_id) REFERENCES matches(id)
);

CREATE TABLE match_participations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    match_id bigint NOT NULL,
    player_id bigint NOT NULL,
    team_id bigint,
    goles integer NOT NULL,
    jugo_efectivamente boolean,
    CONSTRAINT match_participations_pkey PRIMARY KEY (id),
    CONSTRAINT uk_match_participation_match_player UNIQUE (match_id, player_id),
    CONSTRAINT fk6sx9mmvygbscwoy0wnrwbda5c FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT fkftoch6rhny43w3jrrny0h9agd FOREIGN KEY (player_id) REFERENCES players(id),
    CONSTRAINT fk2awn3ocokbpgva8su7to75fu3 FOREIGN KEY (team_id) REFERENCES teams(id)
);

CREATE TABLE match_attendances (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    match_id bigint NOT NULL,
    hincha_id bigint NOT NULL,
    CONSTRAINT match_attendances_pkey PRIMARY KEY (id),
    CONSTRAINT uk_match_attendance_match_hincha UNIQUE (match_id, hincha_id),
    CONSTRAINT fkmdfoywx5pls6cnkouj63x67ub FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT fkh2qoinbqhascw6ypdvojcaa3l FOREIGN KEY (hincha_id) REFERENCES hinchas(id)
);

CREATE TABLE match_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    match_id bigint NOT NULL,
    author_id bigint NOT NULL,
    contenido text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT match_comments_pkey PRIMARY KEY (id),
    CONSTRAINT fkrq6oxrppk4d019f26ua3b807d FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT fk9gobw67c1ntp8qanopq9o0uxw FOREIGN KEY (author_id) REFERENCES users(id)
);

CREATE TABLE ratings (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    match_id bigint NOT NULL,
    calificador_id bigint NOT NULL,
    calificado_id bigint NOT NULL,
    puntaje integer NOT NULL,
    CONSTRAINT ratings_pkey PRIMARY KEY (id),
    CONSTRAINT uk_rating_match_calificador_calificado UNIQUE (match_id, calificador_id, calificado_id),
    CONSTRAINT fkijjij5lge8maflvokogo900i3 FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT fk5btg1snvraaa2v43gi2372v4u FOREIGN KEY (calificador_id) REFERENCES players(id),
    CONSTRAINT fkg7yf4h3sfvp8j10dxm85wvlyb FOREIGN KEY (calificado_id) REFERENCES players(id)
);

CREATE TABLE player_attributes (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    player_id bigint NOT NULL,
    attribute_type varchar(20) NOT NULL,
    current_value double precision NOT NULL,
    CONSTRAINT player_attributes_pkey PRIMARY KEY (id),
    CONSTRAINT uk_player_attribute UNIQUE (player_id, attribute_type),
    CONSTRAINT player_attributes_attribute_type_check CHECK (attribute_type IN ('TECNICA', 'FISICO', 'DEFINICION', 'MENTALIDAD', 'PASE')),
    CONSTRAINT fk5p4dpywpd7e5bpd53s5f2wxfi FOREIGN KEY (player_id) REFERENCES players(id)
);

CREATE TABLE player_attribute_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    player_id bigint NOT NULL,
    attribute_type varchar(20) NOT NULL,
    match_id bigint NOT NULL,
    rating_value integer NOT NULL,
    CONSTRAINT player_attribute_history_pkey PRIMARY KEY (id),
    CONSTRAINT uk_player_attribute_history UNIQUE (player_id, attribute_type, match_id),
    CONSTRAINT player_attribute_history_attribute_type_check CHECK (attribute_type IN ('TECNICA', 'FISICO', 'DEFINICION', 'MENTALIDAD', 'PASE')),
    CONSTRAINT fk7uke6ty9ek6f121xehldpevyh FOREIGN KEY (player_id) REFERENCES players(id),
    CONSTRAINT fkff4gwxiapia2o2h3jwyccwnnr FOREIGN KEY (match_id) REFERENCES matches(id)
);